import {
  DECK_COHERENCE_REVIEW_SCRIPT_SEMANTICS_STAGE,
  DECK_COHERENCE_REVIEW_SLIDE_OUTLINE_STAGE,
  DECK_COHERENCE_REVIEW_SLIDE_PLAN_STAGE,
} from '@video-agent/ir'

export const DECK_LLM_CONTENT_ANALYSIS_STAGE = 'content-analysis' as const
export const DECK_LLM_CONTENT_ANALYSIS_MERGE_STAGE = 'content-analysis-merge' as const
export const DECK_LLM_DECK_BRIEF_STAGE = 'deck-brief' as const
export const DECK_LLM_SLIDE_OUTLINE_STAGE = DECK_COHERENCE_REVIEW_SLIDE_OUTLINE_STAGE
export const DECK_LLM_SLIDE_PLAN_STAGE = DECK_COHERENCE_REVIEW_SLIDE_PLAN_STAGE
export const DECK_LLM_SCRIPT_SEMANTICS_STAGE = DECK_COHERENCE_REVIEW_SCRIPT_SEMANTICS_STAGE
export const DECK_LLM_COHERENCE_REVIEW_STAGE = 'coherence-review' as const
export const DECK_LLM_FINAL_BUILD_STAGE = 'final-build' as const

export const DECK_LLM_PLANNING_STAGES = [
  DECK_LLM_CONTENT_ANALYSIS_STAGE,
  DECK_LLM_CONTENT_ANALYSIS_MERGE_STAGE,
  DECK_LLM_DECK_BRIEF_STAGE,
  DECK_LLM_SLIDE_OUTLINE_STAGE,
  DECK_LLM_SLIDE_PLAN_STAGE,
  DECK_LLM_SCRIPT_SEMANTICS_STAGE,
  DECK_LLM_COHERENCE_REVIEW_STAGE,
] as const
export type DeckLLMPlanningStage = (typeof DECK_LLM_PLANNING_STAGES)[number]

export const DECK_LLM_REWRITE_STAGES = [
  DECK_LLM_SLIDE_OUTLINE_STAGE,
  DECK_LLM_SLIDE_PLAN_STAGE,
  DECK_LLM_SCRIPT_SEMANTICS_STAGE,
] as const
export type DeckLLMRewriteStage = (typeof DECK_LLM_REWRITE_STAGES)[number]

export type DeckLLMValidationStage = DeckLLMPlanningStage | typeof DECK_LLM_FINAL_BUILD_STAGE
