import {DECK_HTML_CAPTURE_BACKENDS} from '@video-agent/ir'
import {z} from 'zod'

import {DECK_FRAME_SHARD_BATCH_SHARD_STATUSES, DECK_FRAME_SHARD_BATCH_STATUSES, DECK_FRAME_SHARD_PLAN_STATUSES, DECK_KEYFRAME_CAPTURE_MODES, DECK_KEYFRAME_SOURCES, TIMED_DECK_ARTIFACT_NAME} from './deck-artifact-constants.js'
import {DECK_RENDERER_BACKENDS, DECK_VIDEO_RENDERERS} from '../render/deck-renderers.js'

const DECK_REVIEW_RENDERERS = [...DECK_HTML_CAPTURE_BACKENDS, 'remotion'] as const

export const DeckVoiceoverSchema = z.object({
  duration: z.number().nonnegative(),
  generatedAt: z.string().min(1),
  outputPath: z.string().min(1),
  segments: z.array(z.object({
    duration: z.number().nonnegative(),
    narrationId: z.string().min(1),
    path: z.string().min(1),
    slideId: z.string().min(1),
    start: z.number().nonnegative(),
  }).strict()),
  version: z.literal(1),
}).strict()

export const DeckFrameManifestSchema = z.object({
  capturedFrames: z.number().int().nonnegative().optional(),
  concurrency: z.number().int().positive().optional(),
  duration: z.number().nonnegative(),
  fps: z.number().positive(),
  frameCount: z.number().int().positive(),
  frameEnd: z.number().int().positive().optional(),
  frameStart: z.number().int().positive().optional(),
  frames: z.array(z.object({
    frame: z.number().int().positive(),
    path: z.string().min(1),
    slideId: z.string().min(1),
    time: z.number().nonnegative(),
  }).strict()),
  generatedAt: z.string().min(1),
  outputDir: z.string().min(1),
  pattern: z.string().min(1),
  renderer: z.enum(DECK_HTML_CAPTURE_BACKENDS),
  skippedFrames: z.number().int().nonnegative().optional(),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME).optional(),
  sourceSha256: z.string().min(1),
  version: z.literal(1),
  viewport: z.object({
    height: z.number().int().positive(),
    width: z.number().int().positive(),
  }).strict(),
}).strict()

export const DeckFrameShardSchema = z.object({
  capturedFrames: z.number().int().nonnegative(),
  concurrency: z.number().int().positive(),
  finalized: z.literal(false),
  fps: z.number().positive(),
  frameCount: z.number().int().positive(),
  frameEnd: z.number().int().positive(),
  frameStart: z.number().int().positive(),
  frames: z.array(z.object({
    frame: z.number().int().positive(),
    path: z.string().min(1),
    slideId: z.string().min(1),
    time: z.number().nonnegative(),
  }).strict()),
  generatedAt: z.string().min(1),
  outputDir: z.string().min(1),
  renderer: z.enum(DECK_HTML_CAPTURE_BACKENDS),
  skippedFrames: z.number().int().nonnegative(),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  sourceSha256: z.string().min(1),
  version: z.literal(1),
}).strict()

export const DeckFrameShardPlanSchema = z.object({
  completeShards: z.number().int().nonnegative(),
  duration: z.number().nonnegative(),
  finalizeArgs: z.array(z.string()),
  fps: z.number().positive(),
  frameCount: z.number().int().positive(),
  frameManifestPath: z.string().min(1),
  frameShardSize: z.number().int().positive(),
  generatedAt: z.string().min(1),
  outputDir: z.string().min(1),
  partialShards: z.number().int().nonnegative(),
  pendingShards: z.number().int().nonnegative(),
  renderer: z.enum(DECK_HTML_CAPTURE_BACKENDS),
  shards: z.array(z.object({
    commandArgs: z.array(z.string()),
    existingFrames: z.number().int().nonnegative(),
    frameCount: z.number().int().positive(),
    frameEnd: z.number().int().positive(),
    frameStart: z.number().int().positive(),
    missingFrameSamples: z.array(z.object({
      frame: z.number().int().positive(),
      path: z.string().min(1),
    }).strict()),
    missingFrames: z.number().int().nonnegative(),
    shardArtifactPath: z.string().min(1),
    status: z.enum(DECK_FRAME_SHARD_PLAN_STATUSES),
  }).strict()),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  sourceSha256: z.string().min(1),
  version: z.literal(1),
}).strict()

export const DeckFrameShardBatchSchema = z.object({
  completedShards: z.number().int().nonnegative(),
  duration: z.number().nonnegative(),
  failedShards: z.number().int().nonnegative(),
  fps: z.number().positive(),
  frameCapturedCount: z.number().int().nonnegative(),
  frameConcurrency: z.number().int().positive(),
  frameCount: z.number().int().positive(),
  frameManifestPath: z.string().min(1),
  frameShardSize: z.number().int().positive(),
  frameSkippedCount: z.number().int().nonnegative(),
  generatedAt: z.string().min(1),
  htmlOutputDir: z.string().min(1),
  outputDir: z.string().min(1),
  renderer: z.enum(DECK_HTML_CAPTURE_BACKENDS),
  shardConcurrency: z.number().int().positive(),
  shardRetryDelayMs: z.number().int().nonnegative(),
  shardRetries: z.number().int().nonnegative(),
  shards: z.array(z.object({
    artifactPath: z.string().min(1).optional(),
    attempts: z.number().int().positive(),
    capturedFrames: z.number().int().nonnegative(),
    error: z.string().min(1).optional(),
    frameCount: z.number().int().positive(),
    frameEnd: z.number().int().positive(),
    frameStart: z.number().int().positive(),
    skippedFrames: z.number().int().nonnegative(),
    status: z.enum(DECK_FRAME_SHARD_BATCH_SHARD_STATUSES),
  }).strict()),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  sourceSha256: z.string().min(1),
  status: z.enum(DECK_FRAME_SHARD_BATCH_STATUSES),
  version: z.literal(1),
}).strict()

export const DeckRendererBackendProjectSchema = z.object({
  backend: z.enum(DECK_RENDERER_BACKENDS),
  commandCwd: z.string().min(1),
  files: z.record(z.string().min(1), z.string().min(1)),
  fps: z.number().positive(),
  generatedAt: z.string().min(1),
  height: z.number().int().positive().optional(),
  motionTimelinePath: z.string().min(1),
  motionTrackCount: z.number().int().nonnegative(),
  outputDir: z.string().min(1),
  previewCommand: z.array(z.string()),
  projectId: z.string().min(1),
  renderCommand: z.array(z.string()),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  sourceSha256: z.string().min(1),
  version: z.literal(1),
  width: z.number().int().positive().optional(),
}).strict()

export const DeckRendererRemotionOutputSchema = z.object({
  backend: z.literal('remotion'),
  command: z.array(z.string().min(1)),
  commandCwd: z.string().min(1),
  completedAt: z.string().min(1),
  exportArtifactPath: z.string().min(1),
  outputPath: z.string().min(1),
  rendererProjectDir: z.string().min(1),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  sourceSha256: z.string().min(1),
  stderr: z.string(),
  stdout: z.string(),
  version: z.literal(1),
}).strict()

export const DeckKeyframesSchema = z.object({
  captureMode: z.enum(DECK_KEYFRAME_CAPTURE_MODES).optional(),
  duration: z.number().nonnegative(),
  fps: z.number().positive(),
  generatedAt: z.string().min(1),
  renderer: z.enum(DECK_REVIEW_RENDERERS),
  samples: z.array(z.object({
    capturedAt: z.string().min(1),
    error: z.string().min(1).optional(),
    frame: z.number().int().positive(),
    label: z.string().min(1),
    ok: z.boolean(),
    path: z.string().min(1),
    sha256: z.string().min(1).optional(),
    size: z.number().int().nonnegative().optional(),
    slideId: z.string().min(1),
    time: z.number().nonnegative(),
  }).strict()),
  source: z.enum(DECK_KEYFRAME_SOURCES),
  version: z.literal(1),
  viewport: z.object({
    height: z.number().int().positive(),
    width: z.number().int().positive(),
  }).strict(),
}).strict()

export const DeckReviewReportSchema = z.object({
  duration: z.number().nonnegative(),
  format: z.string().min(1),
  generatedAt: z.string().min(1),
  keyframeQualityPath: z.string().min(1),
  outputPath: z.string().min(1),
  projectId: z.string().min(1),
  renderer: z.enum(DECK_REVIEW_RENDERERS),
  reviewHtmlPath: z.string().min(1),
  slides: z.array(z.object({
    chartBars: z.array(z.object({
      caption: z.string().min(1).optional(),
      label: z.string().min(1),
      value: z.number().finite().min(0).max(1),
    }).strict()).optional(),
    duration: z.number().nonnegative(),
    end: z.number().nonnegative(),
    index: z.number().int().positive(),
    keyframe: z.object({
      error: z.string().min(1).optional(),
      ok: z.boolean(),
      path: z.string().min(1),
      sha256: z.string().min(1).optional(),
      size: z.number().int().nonnegative().optional(),
      time: z.number().nonnegative(),
    }).strict().optional(),
    points: z.array(z.string()).optional(),
    slideId: z.string().min(1),
    speakerNote: z.string().optional(),
    start: z.number().nonnegative(),
    title: z.string().min(1),
    type: z.string().min(1),
  }).strict()),
  source: z.literal(TIMED_DECK_ARTIFACT_NAME),
  summary: z.object({
    deckErrors: z.number().int().nonnegative(),
    deckWarnings: z.number().int().nonnegative(),
    keyframes: z.number().int().nonnegative(),
    outputErrors: z.number().int().nonnegative(),
    outputWarnings: z.number().int().nonnegative(),
    slides: z.number().int().nonnegative(),
    subtitleErrors: z.number().int().nonnegative(),
    subtitleWarnings: z.number().int().nonnegative(),
    visualErrors: z.number().int().nonnegative(),
    visualWarnings: z.number().int().nonnegative(),
  }).strict(),
  title: z.string().min(1),
  version: z.literal(1),
  videoRenderer: z.enum(DECK_VIDEO_RENDERERS),
}).strict()
