import type {McpToolDefinition} from './toolkit.js'

import {
  createDeckFinalRenderProject,
  createDeckFrameShardBatchProject,
  createDeckFrameShardPlanProject,
  createDeckRemotionRenderProject,
  createDeckRendererBackendProject,
} from '@video-agent/pipeline-deck'
import {
  booleanSchema,
  createToolDefinition,
  enumSchema,
  integerSchema,
  projectIdSchema,
  readOptionalBoolean,
  readOptionalEnum,
  readOptionalInteger,
  readOptionalString,
  readOptionalStringArray,
  readRequiredString,
  stringArraySchema,
  stringSchema,
} from './toolkit.js'

export const DECK_MCP_TOOL_DEFINITIONS: McpToolDefinition[] = [
  createToolDefinition('video_agent_deck_render', 'Render a Deck Explainer project. Defaults to Remotion; use renderer=html for the slower HTML/Playwright fallback.', {
    chromiumCommand: stringArraySchema('Chromium command prefix for HTML frame capture.'),
    finalize: booleanSchema('Finalize video after a frame range capture when all frames are available.'),
    finalizeOnly: booleanSchema('Finalize from an existing complete Deck frame manifest without launching the browser capture backend.'),
    frameCaptureBackend: enumSchema(['chromium', 'playwright'], 'Browser backend for full frame sequence capture. Defaults to playwright.'),
    frameConcurrency: integerSchema('Maximum browser screenshot captures to run concurrently.'),
    frameEnd: integerSchema('Last 1-based frame number to capture for a frame shard.'),
    frameStart: integerSchema('First 1-based frame number to capture for a frame shard.'),
    htmlOutput: stringSchema('Output path for optional external HTML renderer capture.'),
    htmlRender: booleanSchema('Run an external HTML renderer such as HyperFrames against renders/html.'),
    htmlRenderCommand: stringArraySchema('External HTML renderer command prefix.'),
    htmlValidate: booleanSchema('Run external HTML renderer validation against renders/html.'),
    keyframeCaptureBackend: enumSchema(['chromium', 'playwright'], 'Browser backend for independent keyframe visual QC.'),
    playwrightCommand: stringArraySchema('Playwright capture command prefix.'),
    projectId: projectIdSchema(),
    renderer: enumSchema(['remotion', 'html'], 'Deck video renderer. Defaults to remotion.'),
  }, (args, workspaceDir) => createDeckFinalRenderProject({
    chromiumCommand: readOptionalStringArray(args, 'chromiumCommand'),
    finalize: readOptionalBoolean(args, 'finalize'),
    finalizeOnly: readOptionalBoolean(args, 'finalizeOnly'),
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', ['chromium', 'playwright']),
    frameConcurrency: readOptionalInteger(args, 'frameConcurrency'),
    frameEnd: readOptionalInteger(args, 'frameEnd'),
    frameStart: readOptionalInteger(args, 'frameStart'),
    htmlOutput: readOptionalString(args, 'htmlOutput'),
    htmlRender: readOptionalBoolean(args, 'htmlRender'),
    htmlRenderCommand: readOptionalStringArray(args, 'htmlRenderCommand'),
    htmlValidate: readOptionalBoolean(args, 'htmlValidate'),
    keyframeCaptureBackend: readOptionalEnum(args, 'keyframeCaptureBackend', ['chromium', 'playwright']),
    playwrightCommand: readOptionalStringArray(args, 'playwrightCommand'),
    projectId: readRequiredString(args, 'projectId'),
    renderer: readOptionalEnum(args, 'renderer', ['remotion', 'html']) as 'remotion' | 'html' | undefined,
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_plan_shards', 'Write a Deck frame shard plan and complete planned frame manifest without rendering frames.', {
    frameCaptureBackend: enumSchema(['chromium', 'playwright'], 'Browser backend for planned shard commands. Defaults to playwright.'),
    frameShardSize: integerSchema('Frame count per planned shard.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => createDeckFrameShardPlanProject({
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', ['chromium', 'playwright']),
    frameShardSize: readOptionalInteger(args, 'frameShardSize'),
    projectId: readRequiredString(args, 'projectId'),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_run_shards', 'Capture all Deck frame shards locally with bounded shard concurrency and write a resumable shard batch artifact.', {
    chromiumCommand: stringArraySchema('Chromium command prefix for HTML frame capture.'),
    frameCaptureBackend: enumSchema(['chromium', 'playwright'], 'Browser backend for full frame sequence capture. Defaults to playwright.'),
    frameConcurrency: integerSchema('Maximum browser screenshot captures per shard.'),
    frameShardSize: integerSchema('Frame count per shard.'),
    playwrightCommand: stringArraySchema('Playwright frame capture command prefix.'),
    projectId: projectIdSchema(),
    shardConcurrency: integerSchema('Maximum shards to capture concurrently.'),
    shardRetryDelayMs: integerSchema('Delay between shard retry attempts in milliseconds.'),
    shardRetries: integerSchema('Retry count for each failed frame shard.'),
  }, (args, workspaceDir) => createDeckFrameShardBatchProject({
    chromiumCommand: readOptionalStringArray(args, 'chromiumCommand'),
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', ['chromium', 'playwright']),
    frameConcurrency: readOptionalInteger(args, 'frameConcurrency'),
    frameShardSize: readOptionalInteger(args, 'frameShardSize'),
    playwrightCommand: readOptionalStringArray(args, 'playwrightCommand'),
    projectId: readRequiredString(args, 'projectId'),
    shardConcurrency: readOptionalInteger(args, 'shardConcurrency'),
    shardRetryDelayMs: readOptionalInteger(args, 'shardRetryDelayMs'),
    shardRetries: readOptionalInteger(args, 'shardRetries'),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_export_backend', 'Export a Deck project to an optional Remotion or Motion Canvas backend project.', {
    backend: enumSchema(['motion-canvas', 'remotion'], 'Renderer backend project to generate. Defaults to remotion.'),
    compositionId: stringSchema('Remotion composition id.'),
    fps: integerSchema('Renderer project frames per second.'),
    outputDir: stringSchema('Output directory for the generated backend project.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => createDeckRendererBackendProject({
    backend: readOptionalEnum(args, 'backend', ['motion-canvas', 'remotion']) ?? 'remotion',
    compositionId: readOptionalString(args, 'compositionId'),
    fps: readOptionalInteger(args, 'fps'),
    outputDir: readOptionalString(args, 'outputDir'),
    projectId: readRequiredString(args, 'projectId'),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_render_backend', 'Render a Deck project through an optional external Remotion backend project.', {
    backend: enumSchema(['remotion'], 'Renderer backend to execute. Defaults to remotion.'),
    command: stringArraySchema('External Remotion render command. Defaults to ["bun","run","render"] inside the generated Remotion project.'),
    compositionId: stringSchema('Remotion composition id.'),
    fps: integerSchema('Renderer project frames per second.'),
    outputDir: stringSchema('Output directory for the generated backend project.'),
    outputPath: stringSchema('Expected Remotion output path. Defaults to renders/remotion/out/final.mp4.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => {
    readOptionalEnum(args, 'backend', ['remotion'])

    return createDeckRemotionRenderProject({
      command: readOptionalStringArray(args, 'command'),
      compositionId: readOptionalString(args, 'compositionId'),
      fps: readOptionalInteger(args, 'fps'),
      outputDir: readOptionalString(args, 'outputDir'),
      outputPath: readOptionalString(args, 'outputPath'),
      projectId: readRequiredString(args, 'projectId'),
      workspaceDir,
    })
  }),
]
