import type {McpToolDefinition} from './toolkit.js'

import {
  DECK_FINAL_RENDERERS,
  createDeckFinalRenderProject,
  createDeckFrameShardBatchProject,
  createDeckFrameShardPlanProject,
  createDeckRemotionRenderProject,
  createDeckRendererBackendProject,
} from '@video-agent/pipeline-deck'
import {DECK_HTML_CAPTURE_BACKENDS, DEFAULT_DECK_HTML_CAPTURE_BACKEND} from '@video-agent/ir'
import {DECK_RENDERER_BACKENDS} from '@video-agent/runtime'
import {
  booleanSchema,
  commandArraySchema,
  createToolDefinition,
  enumSchema,
  nonNegativeIntegerSchema,
  positiveIntegerSchema,
  projectIdSchema,
  readOptionalBoolean,
  readOptionalCommandArray,
  readOptionalEnum,
  readOptionalNonNegativeInteger,
  readOptionalPositiveInteger,
  readOptionalString,
  readRequiredEnum,
  readRequiredString,
  stringSchema,
} from './toolkit.js'

export const DECK_MCP_TOOL_DEFINITIONS: McpToolDefinition[] = [
  createToolDefinition('video_agent_deck_render', 'Render a Deck Explainer project. Defaults to Remotion; use renderer=html for the slower HTML/Playwright renderer.', {
    chromiumCommand: commandArraySchema('Chromium command prefix for HTML frame capture.'),
    finalize: booleanSchema('Finalize video after a frame range capture when all frames are available.'),
    finalizeOnly: booleanSchema('Finalize from an existing complete Deck frame manifest without launching the browser capture backend.'),
    frameCaptureBackend: enumSchema(DECK_HTML_CAPTURE_BACKENDS, `Browser backend for full frame sequence capture. Defaults to ${DEFAULT_DECK_HTML_CAPTURE_BACKEND}.`),
    frameConcurrency: positiveIntegerSchema('Maximum browser screenshot captures to run concurrently.'),
    frameEnd: positiveIntegerSchema('Last 1-based frame number to capture for a frame shard.'),
    frameStart: positiveIntegerSchema('First 1-based frame number to capture for a frame shard.'),
    htmlOutput: stringSchema('Output path for optional external HTML renderer capture.'),
    htmlRender: booleanSchema('Run an external HTML renderer such as HyperFrames against renders/html.'),
    htmlRenderCommand: commandArraySchema('External HTML renderer command prefix.'),
    htmlValidate: booleanSchema('Run external HTML renderer validation against renders/html.'),
    keyframeCaptureBackend: enumSchema(DECK_HTML_CAPTURE_BACKENDS, 'Browser backend for independent keyframe visual QC.'),
    playwrightCommand: commandArraySchema('Playwright capture command prefix.'),
    projectId: projectIdSchema(),
    renderer: enumSchema(DECK_FINAL_RENDERERS, 'Deck video renderer. Defaults to remotion.'),
  }, (args, workspaceDir) => createDeckFinalRenderProject({
    chromiumCommand: readOptionalCommandArray(args, 'chromiumCommand'),
    finalize: readOptionalBoolean(args, 'finalize'),
    finalizeOnly: readOptionalBoolean(args, 'finalizeOnly'),
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', DECK_HTML_CAPTURE_BACKENDS),
    frameConcurrency: readOptionalPositiveInteger(args, 'frameConcurrency'),
    frameEnd: readOptionalPositiveInteger(args, 'frameEnd'),
    frameStart: readOptionalPositiveInteger(args, 'frameStart'),
    htmlOutput: readOptionalString(args, 'htmlOutput'),
    htmlRender: readOptionalBoolean(args, 'htmlRender'),
    htmlRenderCommand: readOptionalCommandArray(args, 'htmlRenderCommand'),
    htmlValidate: readOptionalBoolean(args, 'htmlValidate'),
    keyframeCaptureBackend: readOptionalEnum(args, 'keyframeCaptureBackend', DECK_HTML_CAPTURE_BACKENDS),
    playwrightCommand: readOptionalCommandArray(args, 'playwrightCommand'),
    projectId: readRequiredString(args, 'projectId'),
    renderer: readOptionalEnum(args, 'renderer', DECK_FINAL_RENDERERS),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_plan_shards', 'Write a Deck frame shard plan and complete planned frame manifest without rendering frames.', {
    frameCaptureBackend: enumSchema(DECK_HTML_CAPTURE_BACKENDS, `Browser backend for planned shard commands. Defaults to ${DEFAULT_DECK_HTML_CAPTURE_BACKEND}.`),
    frameShardSize: positiveIntegerSchema('Frame count per planned shard.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => createDeckFrameShardPlanProject({
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', DECK_HTML_CAPTURE_BACKENDS),
    frameShardSize: readOptionalPositiveInteger(args, 'frameShardSize'),
    projectId: readRequiredString(args, 'projectId'),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_run_shards', 'Capture all Deck frame shards locally with bounded shard concurrency and write a resumable shard batch artifact.', {
    chromiumCommand: commandArraySchema('Chromium command prefix for HTML frame capture.'),
    frameCaptureBackend: enumSchema(DECK_HTML_CAPTURE_BACKENDS, `Browser backend for full frame sequence capture. Defaults to ${DEFAULT_DECK_HTML_CAPTURE_BACKEND}.`),
    frameConcurrency: positiveIntegerSchema('Maximum browser screenshot captures per shard.'),
    frameShardSize: positiveIntegerSchema('Frame count per shard.'),
    playwrightCommand: commandArraySchema('Playwright frame capture command prefix.'),
    projectId: projectIdSchema(),
    shardConcurrency: positiveIntegerSchema('Maximum shards to capture concurrently.'),
    shardRetryDelayMs: nonNegativeIntegerSchema('Delay between shard retry attempts in milliseconds.'),
    shardRetries: nonNegativeIntegerSchema('Retry count for each failed frame shard.'),
  }, (args, workspaceDir) => createDeckFrameShardBatchProject({
    chromiumCommand: readOptionalCommandArray(args, 'chromiumCommand'),
    frameCaptureBackend: readOptionalEnum(args, 'frameCaptureBackend', DECK_HTML_CAPTURE_BACKENDS),
    frameConcurrency: readOptionalPositiveInteger(args, 'frameConcurrency'),
    frameShardSize: readOptionalPositiveInteger(args, 'frameShardSize'),
    playwrightCommand: readOptionalCommandArray(args, 'playwrightCommand'),
    projectId: readRequiredString(args, 'projectId'),
    shardConcurrency: readOptionalPositiveInteger(args, 'shardConcurrency'),
    shardRetryDelayMs: readOptionalNonNegativeInteger(args, 'shardRetryDelayMs'),
    shardRetries: readOptionalNonNegativeInteger(args, 'shardRetries'),
    workspaceDir,
  })),
  createToolDefinition('video_agent_deck_export_backend', 'Export a Deck project to a Remotion or Motion Canvas backend project.', {
    backend: enumSchema(DECK_RENDERER_BACKENDS, 'Renderer backend project to generate.'),
    compositionId: stringSchema('Remotion composition id.'),
    fps: positiveIntegerSchema('Renderer project frames per second.'),
    outputDir: stringSchema('Output directory for the generated backend project.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => createDeckRendererBackendProject({
    backend: readRequiredEnum(args, 'backend', DECK_RENDERER_BACKENDS),
    compositionId: readOptionalString(args, 'compositionId'),
    fps: readOptionalPositiveInteger(args, 'fps'),
    outputDir: readOptionalString(args, 'outputDir'),
    projectId: readRequiredString(args, 'projectId'),
    workspaceDir,
  }), ['backend', 'projectId']),
  createToolDefinition('video_agent_deck_render_backend', 'Render a Deck project through the external Remotion backend project.', {
    command: commandArraySchema('External Remotion render command. Defaults to ["bun","run","render"] inside the generated Remotion project.'),
    compositionId: stringSchema('Remotion composition id.'),
    fps: positiveIntegerSchema('Renderer project frames per second.'),
    outputDir: stringSchema('Output directory for the generated backend project.'),
    outputPath: stringSchema('Expected Remotion output path. Defaults to renders/remotion/out/final.mp4.'),
    projectId: projectIdSchema(),
  }, (args, workspaceDir) => createDeckRemotionRenderProject({
    command: readOptionalCommandArray(args, 'command'),
    compositionId: readOptionalString(args, 'compositionId'),
    fps: readOptionalPositiveInteger(args, 'fps'),
    outputDir: readOptionalString(args, 'outputDir'),
    outputPath: readOptionalString(args, 'outputPath'),
    projectId: readRequiredString(args, 'projectId'),
    workspaceDir,
  })),
]
